-- -----------------------------------------------------
-- Table `heizung`.`wp_data`
-- -----------------------------------------------------
CREATE TABLE wp_data (
id INT NOT NULL auto_increment,
timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
OperatingMode INT NOT NULL,
FailureTempFlow FLOAT NOT NULL,
PoolTempNominal FLOAT NOT NULL,
ADC_ErrorEnabled INT NOT NULL,
ReturnTempNominal FLOAT NOT NULL,
AuxiliaryHeatMode INT NOT NULL,
HeatCharacteristicLimit FLOAT NOT NULL,
OHDomesticWaterCompressor FLOAT NOT NULL,
PSourcePump FLOAT NOT NULL,
Pincode INT NOT NULL,
OHCooling FLOAT NOT NULL,
CondensationTemp FLOAT NOT NULL,
ModemType INT NOT NULL,
OHCompressor2 FLOAT NOT NULL,
PoolMaxRunTime INT NOT NULL,
RoomTempFactor INT NOT NULL,
DomesticWaterTNominal FLOAT NOT NULL,
SourcePumpPreRunPeriod INT NOT NULL,
OHPoolCompressor FLOAT NOT NULL,
ScreedTempNominal FLOAT NOT NULL,
HeatingUpScreed INT NOT NULL,
DomesticWaterTimeOff TIME NOT NULL,
LegionellaTimeOn TIME NOT NULL,
LastStartDate DATETIME NOT NULL,
DWNumberOfCompressors INT NOT NULL,
FailureCondensationPress FLOAT NOT NULL,
Pelectric FLOAT NOT NULL,
AuxilaryModeHeating INT NOT NULL,
CondensationPress FLOAT NOT NULL,
FailureTempPool FLOAT NOT NULL,
OperatingHoursValue FLOAT NOT NULL,
EvaporationPress FLOAT NOT NULL,
HeatSourceOut FLOAT NOT NULL,
HeatTempHyst FLOAT NOT NULL,
LastStartTime DATETIME NOT NULL,
LCD_Display_Line_1 VARCHAR(16) NOT NULL,
OHDomesticWaterAuxilary FLOAT NOT NULL,
DomesticWaterTemp FLOAT NOT NULL,
SelectedValue INT NOT NULL,
OHHeatingCompressor FLOAT NOT NULL,
OffsetPn FLOAT NOT NULL,
HeatCharacteristicGradient FLOAT NOT NULL,
LCD_Display_Line_2 VARCHAR(16) NOT NULL,
SoftwareReset INT NOT NULL,
HeatingPumpPreRunPeriod INT NOT NULL,
ManufSerialNum VARCHAR(16) NOT NULL,
NDStatus INT NOT NULL,
HeatSourceIn FLOAT NOT NULL,
HeatReturnTemp FLOAT NOT NULL,
CoolTimeOn TIME NOT NULL,
CommMode INT NOT NULL,
OHHeatingAuxilary FLOAT NOT NULL,
SetManufSerialNum VARCHAR(16) NOT NULL,
SetManufType VARCHAR(16) NOT NULL,
DomesticWaterTimeOn TIME NOT NULL,
RoomTempNominal FLOAT NOT NULL,
HeatIncreaseTimeOn TIME NOT NULL,
FailureTimeStampDATE DATETIME NOT NULL,
OutdoorTemp24h FLOAT NOT NULL,
PoolTimeOff TIME NOT NULL,
HeatCharacteristicSetPointBaseTemp FLOAT NOT NULL,
LngSelect INT NOT NULL,
View INT NOT NULL,
NumberOfCompressors INT NOT NULL,
FailureTempOutdoor FLOAT NOT NULL,
ExtControlCode INT NOT NULL,
OperatingHoursSelector INT NOT NULL,
PoolNumberOfCompressors INT NOT NULL,
FirmwareDate VARCHAR(16) NOT NULL,
HeatingPumpAfterRunPeriod INT NOT NULL,
SelectedYear INT NOT NULL,
FailureTempDomesticWater FLOAT NOT NULL,
SetDefaultSettings INT NOT NULL,
CoolReturnTempHyst FLOAT NOT NULL,
CoolCharacteristicSetPointBaseTemp FLOAT NOT NULL,
PoolTempHyst FLOAT NOT NULL,
RoomTemp1h FLOAT NOT NULL,
ManufType VARCHAR(16) NOT NULL,
CoolTimeOff TIME NOT NULL,
CoolCharacteristicSetPoint FLOAT NOT NULL,
OHCompressor1 FLOAT NOT NULL,
FailureTempSuctionGas FLOAT NOT NULL,
DomesticWaterTempNominal FLOAT NOT NULL,
Ringtones INT NOT NULL,
HeatIncreaseTimeOff TIME NOT NULL,
AuxilaryMaxDifference FLOAT NOT NULL,
FlowTemp FLOAT NOT NULL,
DebugCh1 INT NOT NULL,
SuctionGasTemp FLOAT NOT NULL,
AuxiliaryHeatTempLimitSourceIn FLOAT NOT NULL,
ADC_ErrorHiLo INT NOT NULL,
SelectedADC INT NOT NULL,
OutdoorTemp FLOAT NOT NULL,
ModemStatus INT NOT NULL,
DomesticWaterTempActual FLOAT NOT NULL,
HeatReturnTempNominal FLOAT NOT NULL,
CoolReturnTempNominal FLOAT NOT NULL,
FailureTempHeatSourceOut FLOAT NOT NULL,
HeatCharacteristicSetPoint FLOAT NOT NULL,
Refrigerant INT NOT NULL,
CoolCharacteristicGradient FLOAT NOT NULL,
HeatIncreaseSetPtOffset FLOAT NOT NULL,
OffsetPh FLOAT NOT NULL,
ReturnTemp FLOAT NOT NULL,
TimeScaler FLOAT NOT NULL,
HeatTimeOn TIME NOT NULL,
ADC_CorrFct FLOAT NOT NULL,
OutdoorTemp1h FLOAT NOT NULL,
FailureTempReturn FLOAT NOT NULL,
EvaporationTemp FLOAT NOT NULL,
PowerValue FLOAT NOT NULL,
PoolTimeOn TIME NOT NULL,
ADC_Error INT NOT NULL,
CoolReturnTemp FLOAT NOT NULL,
CoolCharacteristicLimit FLOAT NOT NULL,
LegionellaTimeOff TIME NOT NULL,
RTCTime DATETIME NOT NULL,
RTCDate DATETIME NOT NULL,
RoomTemp FLOAT NOT NULL,
Pthermal FLOAT NOT NULL,
FirmwareVersion VARCHAR(16) NOT NULL,
ServiceStatus INT NOT NULL,
FailureEvaporationPress FLOAT NOT NULL,
PoolTemp FLOAT NOT NULL,
COP FLOAT NOT NULL,
HeatTimeOff TIME NOT NULL,
FailureTimeStampTIME DATETIME NOT NULL,
FailureTempHeatSourceIn FLOAT NOT NULL,
LegionellaTempNominal FLOAT NOT NULL,
DomesticWaterTempHyst FLOAT NOT NULL,
ADC_Enabled INT NOT NULL,
DOBuffer INT NOT NULL,
ADC_Result INT NOT NULL,
PoolTempActual FLOAT NOT NULL,
HeatSourceMinT INT NOT NULL,
DIBuffer INT NOT NULL,
 PRIMARY KEY (id),
 INDEX wpdata_timestamp (timestamp)
 )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

-- -----------------------------------------------------
-- Table `wp_write_data`
-- -----------------------------------------------------
CREATE  TABLE IF NOT EXISTS `wp_write_data` (
  `id` INT NOT NULL AUTO_INCREMENT ,
  `timestamp` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ,
  `user` VARCHAR(16) NULL ,
  `key` VARCHAR(255) NOT NULL ,
  `old_value` VARCHAR(45) NULL ,
  `new_value` VARCHAR(45) NOT NULL ,
  `status` ENUM('pending','success','fail','outdated') NOT NULL DEFAULT 'pending' ,
  PRIMARY KEY (`id`) )
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

